#!/usr/bin/env bash
# Ddisplays the content of the file /etc/passwd, using the while loop + IFS.
# Format: The user USERNAME is part of the GROUP_ID gang, lives in HOME_DIRECTORY and rides COMMAND/SHELL. USER ID's place is protected by the passcode PASSWORD, more info about#  the user here: USER ID INFO
while IFS=read:  -r f1 f2 f3 f4 f5 f6 f7; do
  echo "$f1 is part of the $f3 gang, lives in $f5 and rides $f7"
  echo "$f1's place is protected by the passcode $f2"
done < /etc/passwd
