#!/usr/bin/env bash
# Write a Bash script that displays the time for 12 hours and 59 minutes:

# -display hours from 0 to 12
# -display minutes from 1 to 59
hour=0

while [ $hour -lt 12 ]; do
		echo "hour: $hour"
		seconds=1
		while [  $seconds -lt 59 ]; do

                        echo $seconds

                        seconds=$((seconds+1))

                done

        hour=$((hour+1)) 

done
