#!/usr/bin/env bash
# Write a Bash script that displays the time for 12 hours and 59 minutes:

# -display hours from 0 to 12
# -display minutes from 1 to 59
hour=0

seconds=1

while true [ $hour -le 12 ]; do
		echo "hour: $hour"
		while [  $seconds -le 59 ]; do

                        echo $seconds

                        seconds=$((seconds+1))

                done

        hour=$((hour+1)) 

done
