#!/usr/bin/env bash
# Write a Bash script that displays:

# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed.
for filename in *
do
  if [ "$filename" != "." ] && [ "$filename" != ".." ]
  then
    echo "${filename:1}"
  fi
done
